name: wanderers_compass
description: a compass for wanderers; a calendar for aliens
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.38.0

resolution: workspace

dependencies:
  authentication_repository: 
    path: 'packages/authentication_repository'
  bloc: ^9.0.1
  build_runner: ^2.10.2
  clock: ^1.1.2
  compass_api:
    path: 'packages/compass_api'
  compass_repository:
    path: 'packages/compass_repository'
  dart_mappable: ^4.6.1
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  formz: ^0.8.0
  go_router: ^17.0.1
  intl: ^0.20.2
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  shared: 0.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  bloc_test: ^10.0.0
  dart_mappable_builder: ^4.6.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
