name: postgres_schedule_data_source
description: Postgres implementation of schedule data source
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies: 
  postgres: ^3.5.9
  schedule_data_source:
    path: '../schedule_data_source'
  shared:
    path: '../../../shared'
  stormberry: ^0.18.0

dev_dependencies:
  build_runner: ^2.10.4
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
