// This file is "model.dart"
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'foothold.schema.dart';

mixin Actor on Foothold {
  Future<void> performAction() async {}
}

mixin Counter on Foothold {
  void decrement() {}

  void increment() {}
}

@Model()
abstract class Foothold {
  @PrimaryKey()
  @AutoIncrement()
  int get id;

  String get name;
}

mixin Memorable on Foothold {
  final bool canComplete = false;
}

mixin Tracker on Foothold {
  void updateProgress() {}
}
