name: pg_compass_datasource
description: Postgres implementation of schedule data source
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies: 
  compass_datasource:
    path: '../compass_datasource'
  postgres: ^3.5.9
  shared:
    path: '../../../shared'
  stormberry: ^0.18.0

dev_dependencies:
  build_runner: ^2.10.4
  dart_mappable: ^4.6.1
  dart_mappable_builder: ^4.6.0
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
