// This file is "model.dart"
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'schedule.schema.dart';

@Model()
abstract class Schedule {
  List<String> get footholds;

  @PrimaryKey()
  @AutoIncrement()
  int get id;

  int get workingHours;
}
