// This file is "model.dart"

import 'package:postgres_compass_datasource/src/models/zone.dart';
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'schedule.schema.dart';

@Model()
abstract class Schedule {
  DateTime get dayEnd;
  DateTime get dayStart;

  List<String> get footholds;

  @PrimaryKey()
  @AutoIncrement()
  int get id;

  String get name;

  @BindTo(#schedule)
  List<Zone>? get zones;
}
