// This file is "model.dart"
import 'package:postgres_compass_datasource/postgres_compass_datasource.dart';
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'zone.schema.dart';

@Model()
abstract class Zone {
  List<String> get footholds;

  @PrimaryKey()
  @AutoIncrement()
  int get id;

  String get name;

  @BindTo(#zones)
  @HiddenIn.defaultView()
  Schedule get schedule;

  DateTime get start;

  DateTime get stop;
}
